application: plannerapp-1031
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /app/scripts
  static_dir: app/scripts
  expiration: "1d 0m"

- url: /app/partials
  static_dir: app/partials
  expiration: "1d 0m"

- url: /app/styles
  static_dir: app/styles
  expiration: "1d 0m"

- url: /app/vendor
  static_dir: app/vendor
  expiration: "1d 0m"

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest